baseURL = 'https://jaigansa.github.io/'
languageCode = 'en-US'
title = 'Jaigansa'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Projects'
pageRef = '/projects'
weight = 20

[[menus.main]]
name = 'Abouts'
pageRef = '/abouts'
weight = 30

[params]
  author_name = "Jai Ganesh"
  tagline = "A Web Developer focused on performance and clean code."