baseURL = 'https://jaigansa.github.io/'
languageCode = 'en-US'
title = 'JAIGANESH'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Projects'
pageRef = '/projects'
weight = 20

[[menus.main]]
name = 'Abouts'
pageRef = '/abouts'
weight = 30

[params]
  author_name = "Jai Ganesh"
  tagline = "A Web Developer focused on performance and clean code."



[build]
  # CRITICAL: This enables Hugo to create hugo_stats.json, 
  # which Tailwind uses to find all classes across your site.
  writeStats = true 

  # These settings tell Hugo to clear its CSS cache and rebuild 
  # the stylesheet whenever your config files change.
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'
  [[build.cachebusters]]
    source = '(postcss|tailwind)\.config\.js'
    target = 'css'

[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  
  # CRITICAL: This tells Hugo to watch the hugo_stats.json file
  # as a standard asset. The disableWatch = true setting tells 
  # the asset watcher not to watch it, as we use cachebusters above.
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'