baseURL = 'https://jaigansa.github.io/'
languageCode = 'en-US'
title = 'Jaigansa'
theme = "jaigansa"

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Projects'
pageRef = '/projects'
weight = 20

[[menus.main]]
name = 'Abouts'
pageRef = '/abouts'
weight = 30

