languageCode = "en"
languageName = "English"
weight = 1
title = "jaigansa"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/logo.png"
  secondaryLogo = "img/logo.png"
  description = "Creative Welder, Digital Artist"
  copyright = "Copy, _right?_ :thinking_face:"

 [author]
   name = "JAI GANESH"
   image = "img/avatar.png"
   headline = "Creative Welder"
   bio = "A little bit about you"
   links = [
     { email = "mailto:jaigansa+ws@gmail.com" },
     { link = "https://jaigansa.github.io/" },
#     { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
#     { apple = "https://www.apple.com" },
     { blogger = "https://jaigansa.blogspot.com/" },
     { codepen = "https://codepen.io/jaigansa" },
#     { dev = "https://dev.to/username" },
     { discord = "https://discord.gg/bfmNqd3ntC" },
#     { dribbble = "https://dribbble.com/username" },
     { facebook = "https://facebook.com/jaigansa" },
#     { flickr = "https://www.flickr.com/photos/username/" },
#     { foursquare = "https://foursquare.com/username" },
     { github = "https://github.com/jaigansa" },
#     { gitlab = "https://gitlab.com/username" },
#     { google = "https://www.google.com/" },
#     { hashnode = "https://username.hashnode.dev" },
     { instagram = "https://instagram.com/jaigansa" },
#     { keybase = "https://keybase.io/username" },
#     { kickstarter = "https://www.kickstarter.com/profile/username" },
#     { lastfm = "https://lastfm.com/user/username" },
     { linkedin = "https://linkedin.com/in/jaigansa" },
#     { mastodon = "https://mastodon.instance/@username" },
#     { medium = "https://medium.com/username" },
#     { microsoft = "https://www.microsoft.com/" },
#     { orcid = "https://orcid.org/userid" },
#     { patreon = "https://www.patreon.com/username" },
#     { pinterest = "https://pinterest.com/username" },
#     { reddit = "https://reddit.com/user/username" },
#     { researchgate = "https://www.researchgate.net/profile/username" },
#     { slack = "https://workspace.url/team/userid" },
#     { snapchat = "https://snapchat.com/add/username" },
#     { soundcloud = "https://soundcloud.com/username" },
#     { stack-overflow = "https://stackoverflow.com/users/userid/username" },
#     { steam = "https://steamcommunity.com/profiles/userid" },
     { telegram = "https://t.me/jaigansa" },
#     { tiktok = "https://tiktok.com/@username" },
#     { tumblr = "https://username.tumblr.com" },
     { twitch = "https://twitch.tv/jaigansa" },
     { twitter = "https://twitter.com/jaigansa" },
#     { x-twitter = "https://twitter.com/username" },
#     { whatsapp = "https://wa.me/phone-n" },
     { youtube = "https://youtube.com/@jaigansa" },
#     { ko-fi = "https://ko-fi.com/username" },
   ]
