languageCode = "en"
languageName = "English"
weight = 1
title = "JaiGanesh"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 Jan 2006" 
  logo = "img/logo.webp"
  description = "jaiganesh own info website"
  copyright = "© 2025 Jaiganesh"

 [params.author]
   name = "JaiGanesh"
   emailid = "jaigansa@outlook.com"
   image = "img/ai_studio_2.webp"
   headline = "Welder"
   bio = "welder"
   links = [
      { youtube = "https://youtube.com/@jaigansa" },
      { discord = "https://discord.gg/sMmeDGchfY" },
      { github = "https://github.com/jaigansa" },
      
   ]

