languageCode = "en"
languageName = "English"
weight = 1
title = "JaiGanesh"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2006 Jan 01" 
  logo = "img/logo.png"
  secondaryLogo = "img/logo.png"
  description = "Personal site"
  copyright = "© 2023 Jaiganesh"

 [author]
   name = "Jaiganesh"
   image = "img/logo.png"
   headline = "human"
   bio = "welder"
   links = [
      { github = "https://github.com/jaigansa" },
     { youtube = "https://youtube.com/@jaigansa" }
   ]
