# -- Main Menu --

[[main]]
  name = "Docs"
  pre = "user"
  pageRef = "docs"
  weight = 10

[[main]]
  name = "Posts"
  pre = "icons-solid"
  pageRef = "posts"
  weight = 30



[[main]]
  name = "Tags"
  pre = "tag"
  pageRef = "tags"
  weight = 80
  
[[main]]
  name = "About"
  pre = "user"
  pageRef = "about"
  weight = 90



# -- Footer Menu --



# Links

[[footer]]
  identifier = "youtube"
  name = "Youtube"
  pre = "youtube"
  url = "https://www.youtube.com/@jaigansa?sub_confirmation=1"
  weight = 10

[[footer]]
  identifier = "github"
  name = "github"
  pre = "github"
  url = "https://github.com/jaigansa"
  weight = 20

 
