# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "About"
  pre = "user"
  pageRef = "about"
  weight = 10

[[main]]
  name = "Docs"
  pre = "file-solid"
  pageRef = "docs"
  weight = 20

[[main]]
  name = "Posts"
  pre = "icons-solid"
  pageRef = "posts"
  weight = 30




[[main]]
  name = "Tags"
  pageRef = "tags"
  weight = 90
# Links

[[main]]
  identifier = "youtube"
  pre = "play-solid"
  url = "https://youtube.com/@jaigansa"
  weight = 100

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/jaigansa"
  weight = 300


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

 
