# -- Theme Options --

 colorScheme = "neon"
 defaultAppearance = "dark" # valid options: light or dark
 autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true

# mainSections = ["section1", "section2"]
# robots = ""

disableImageOptimization = false

# defaultBackgroundImage = "IMAGE.jpg" # used as default for background images 
# defaultFeaturedImage = "IMAGE.jpg" # used as default for featured images in all articles

 highlightCurrentMenuArea = true
 smartTOC = true
 smartTOCHideUnfocusedChildren = true

[header]
  layout = "fixed-fill-blur" # valid options: basic, fixed, fixed-fill, fixed-fill-blur
  showAppearanceSwitcher = true

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = false
  showScrollToTop = true

[homepage]
  layout = "background" # valid options: page, profile, hero, card, background, custom
  homepageImage = "img/avatar.png" # used in: hero, and card
  showRecent = true
  showRecentItems = 6
  showMoreLink = true
  showMoreLinkDest = "/posts"
  cardView = true
  cardViewScreenWidth = true
  layoutBackgroundBlur = true # only used when layout equals background

[article]
  showDate = false
  showViews = false
  showLikes = true
  showDateUpdated = true
  showAuthor =  true
  showHero = true
  heroStyle = "thumbAndBackground" # valid options: basic, big, background, thumbAndBackground
  layoutBackgroundBlur = true # only used when heroStyle equals background or thumbAndBackground
  layoutBackgroundHeaderSpace = true # only used when heroStyle equals background
  showBreadcrumbs = false
  showDraftLabel = false
  showEdit = false
  # editURL = "https://github.com/jaigansa/jaigansa.github.io/tree/main"
  editAppendPath = false
  seriesOpened = false
  showHeadingAnchors = false
  showPagination = true
  invertPagination = false
  showReadingTime = false
  showTableOfContents = true
  showRelatedContent = true
  relatedContentLimit = 3
  showTaxonomies = true
  showAuthorsBadges = true
  showWordCount = true
  showComments = true
  sharingLinks = [ "linkedin", "twitter", "reddit", "pinterest", "facebook", "email", "whatsapp", "telegram"]

[list]
  showHero = true
  heroStyle = "thumbAndBackground" # lid options: basic, big, background, thumbAndBackground
  layoutBackgroundBlur = true # only used when heroStyle equals background or thumbAndBackground
  layoutBackgroundHeaderSpace = true # only used when heroStyle equals background
  showBreadcrumbs = false
  showSummary = false
  showViews = false
  showLikes = false
  showTableOfContents = true
  showCards = true
  groupByYear = false
  cardView = true
  cardViewScreenWidth = true
  constrainItemsWidth = true


[sitemap]
  excludedKinds = ["taxonomy", "term"]

[taxonomy]
  showTermCount = true
  showHero = true
  heroStyle = "thumbAndBackground" # valid options: basic, big, background, thumbAndBackground
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = false
  cardView = true

[term]
  showHero = true
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = true
  groupByYear = false
  cardView = true
  cardViewScreenWidth = false

[firebase]
    apiKey = "AIzaSyCUXUfOxxWxKLO0P9n15bna_FpRdLcav8Q"
    authDomain = "views-likes-597ae.firebaseapp.com"
    projectId = "views-likes-597ae"
    storageBucket = "views-likes-597ae.appspot.com"
    messagingSenderId = "1098494142337"
    appId = "1:1098494142337:web:664bec15c7fa3c420d6a80"
    measurementId = "G-JB7YCJ7392"

[fathomAnalytics]
  # site = "ABC12345"
  # domain = "llama.yoursite.com"

[buymeacoffee]
  # identifier = ""
  # globalWidget = true
  # globalWidgetMessage = "Hello"
  # globalWidgetColor = "#FFDD00"
  # globalWidgetPosition = "Right"

[verification]
  # google = ""
  # bing = ""
  # pinterest = ""
  # yandex = ""
