# -- Theme Options --

 colorScheme = "nord"
 defaultAppearance = "dark" # valid options: light or dark
 autoSwitchAppearance = true

 enableSearch = true
 enableCodeCopy = true

 replyByEmail = false


 mainSections = ["posts", "docs"]
# robots = ""

 disableImageOptimization = true
 disableTextInHeader = true
 backgroundImageWidth = 1200

 defaultBackgroundImage = "img/ai_studio_1.webp" 
 defaultFeaturedImage = "img/featured.webp" 

 highlightCurrentMenuArea = true
 martTOC = true
 smartTOCHideUnfocusedChildren = false

[header]
  layout = "basic" # valid options: basic, fixed, fixed-fill, fixed-fill-blur

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "profile" # valid options: page, profile, hero, card, background, custom
# homepageImage = "img/ai_studio_1.webp" # used in: hero, and card
  showRecent = true
  showRecentItems = 6
  showMoreLink = true
  showMoreLinkDest = "posts" 
  cardView = true
  cardViewScreenWidth = false
  layoutBackgroundBlur = false # only used when layout equals background

[article]
  showDate = true
  showViews = true
  showLikes = true
  showDateOnlyInArticle = true
  showDateUpdated = false
  showAuthor = true
  showAuthorBottom = true
  showHero = true
  heroStyle = "big" # valid options: basic, big, background, thumbAndBackground
  layoutBackgroundBlur = false # only used when heroStyle equals background
  showBreadcrumbs = false
  showDraftLabel = true
  showEdit = true
  editURL = "https://github.com/jaigansa/jaigansa.github.io/tree/main/content"
  editAppendPath = true
  seriesOpened = false
  showHeadingAnchors = false
  showPagination = false
  invertPagination = false
  showReadingTime = false
  showTableOfContents = true
  showRelatedContent = true
  relatedContentLimit = 3
  showTaxonomies = true
  showAuthorsBadges = false
  showWordCount = false
  sharingLinks = [ "whatsapp", "telegram", "facebook",  ]
  showZenMode = true

[list]
  showHero = false
  heroStyle = "basic" # valid options: basic, big, background, thumbAndBackground
  layoutBackgroundBlur = false # only used when heroStyle equals background
  layoutBackgroundHeaderSpace = false
  showBreadcrumbs = false
  showSummary = true
  showLikes = false
  showTableOfContents = false
  showCards = false
  orderByWeight = false
  groupByYear = false
  cardView = false
  cardViewScreenWidth = false
  constrainItemsWidth = false

[sitemap]
  excludedKinds = ["taxonomy", "term"]

[taxonomy]
  showTermCount = true
  showHero = true
  heroStyle = "big" # valid options: basic, big, background, thumbAndBackground
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = true
  cardView = false

[term]
  showHero = true
  heroStyle = "big" # valid options: basic, big, background, thumbAndBackground
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = true
  groupByYear = false
  cardView = true
  cardViewScreenWidth = true

[firebase]
    apiKey = "AIzaSyCUXUfOxxWxKLO0P9n15bna_FpRdLcav8Q"
    authDomain = "views-likes-597ae.firebaseapp.com"
    projectId = "views-likes-597ae"
    storageBucket = "views-likes-597ae.appspot.com"
    messagingSenderId = "1098494142337"
    appId = "1:1098494142337:web:664bec15c7fa3c420d6a80"
    measurementId = "G-JB7YCJ7392"

[fathomAnalytics]
  # site = "ABC12345"
  # domain = "llama.yoursite.com"

[umamiAnalytics]
  # websiteid = "ABC12345"
  # domain = "llama.yoursite.com"

[buymeacoffee]
  # identifier = ""
  # globalWidget = true
  # globalWidgetMessage = "Hello"
  # globalWidgetColor = "#FFDD00"
  # globalWidgetPosition = "Right"

[verification]
  # google = ""
  # bing = ""
  # pinterest = ""
  # yandex = ""
